import os
from PIL import Image

# Cewe Background Resources Folder (single colors only for now)
ceweRes = "C:\\<PathToCeweInstallation>\\Resources\\photofun\\backgrounds\\einfarbige\\"

# the c# file to generate
csharp = "\\..\\Cewe2pdf\\DesignIdData.cs"


out =  "/*******************************************************************/\n"
out += "/************     auto generated by 'cewe2data.py'     *************/\n"
out += "/*******************************************************************/\n\n"
out += "using System.Collections.Generic;\n"
out += "using iTextSharp.text;\n"
out += "\nnamespace Cewe2pdf {\n"
out += "\tpublic class DesignIdDatabase {\n"
out += "\t\tpublic static Dictionary<string, BaseColor> backgroundColors = new Dictionary<string, BaseColor>() {\n"

directory = os.fsencode(ceweRes)

for file in os.listdir(directory):
    filename = os.fsdecode(file)
    if filename.endswith(".webp"):
        path = ceweRes + filename
        img = Image.open(path)
        rgb_img = img.convert('RGB')
        r, g, b = rgb_img.getpixel((1, 1))
        print("image: " + filename[:-5] + " rgb: " + str(r) + ", " + str(g) + ", " + str(b) + ".")
        out += "\t\t\t{\"" + filename[:-5] + "\", new BaseColor(" + str(r) + ", " + str(g) + ", " + str(b) + ")},\n"
        # handle some special numbers that may be leftovers from earlier cewe versions or whatever
        if (filename[:-5] == "6015"):
            out += "\t\t\t{\"" + "211" + "\", new BaseColor(" + str(r) + ", " + str(g) + ", " + str(b) + ")},\n"
            
out += "\t\t};\n"
out += "\t}\n}\n"

csfile = open(csharp,"w")
csfile.write(out)
csfile.close()